-- Création de la table pour stocker les conversations
create table if not exists "public"."67beb8130dc403377ca266db_chat_conversations" (
  "id" uuid primary key default uuid_generate_v4(),
  "user_id" uuid,
  "title" text,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now()
);

-- Création de la table pour stocker les messages individuels
create table if not exists "public"."67beb8130dc403377ca266db_chat_messages" (
  "id" bigint generated by default as identity,
  "conversation_id" uuid references "public"."67beb8130dc403377ca266db_chat_conversations" ("id") on delete cascade,
  "role" text not null,
  "content" text not null,
  "timestamp" timestamptz default now(),
  
  primary key ("id")
);

-- Index pour optimiser les recherches par conversation
create index if not exists "idx_chat_messages_conversation_id" on "public"."67beb8130dc403377ca266db_chat_messages" ("conversation_id");